# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170211_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
