# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170211_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='approve',
            field=models.BooleanField(default='False'),
        ),
    ]
