# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_grant_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscribedgrant',
            name='grant_id',
        ),
        migrations.RemoveField(
            model_name='usersubscribedgrant',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='approve',
        ),
        migrations.DeleteModel(
            name='UserSubscribedGrant',
        ),
    ]
