# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170923_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
